version: 0.2

# Declaration of environment variables
env:
 variables:
  CODE_BUILD_BUCKET: "codepipeline-us-east-1-398615444244"
            
phases:
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket ${CODE_BUILD_BUCKET} --output-template-file outputTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml