version: 0.2

phases:
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket milad-test --output-template-file outputTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml