version: 0.2

phases:

  install:
    commands:
      - go get github.com/aws/aws-lambda-go/lambda

  build:
    commands:
      - go build -o main
      - aws cloudformation package --template-file template.yaml --s3-bucket milad-test --output-template-file outputTemplate.yaml --stack-name milad_test
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml
    - template-config.json