AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'milad test webhook'

# Parameters
Parameters:
  FunctionName:
    Type: String
    Description: Funciton Name
    Default: my-deployment-bucket
  Env:
    Type: String
    AllowedValues:
    - _dev
    - _tst
    - _prd
  UserEnv:
    Type: String

Resources:
  miladTestWebhook:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: go1.x
      Handler: main
      AutoPublishAlias: live
      Tracing: Active
      FunctionName: !Join [ "", [ !Ref FunctionName, "-api-thing-get"]]
      DeploymentPreference:
        Type: AllAtOnce
      Tags:
        AppNameTag: !Ref AWS::Region
      Environment:
        Variables:
          Env1: '{"REGION": "REGION_VALUE", "ENDPOINT": "http://SOME_ENDPOINT"}'
          Env2: !Ref 'FunctionName'
          MyEnvironment : stage
          USERENV: !Ref UserEnv
          ENV: !Ref Env

  DynamoDBTableProducts:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Join [ "", [ "Products", !Ref Env]]
      AttributeDefinitions:
        - AttributeName: 'productId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'productId'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 20