AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'milad test webhook'

# Parameters
Parameters:
  PullRequest:
    Type: String
    Default: 'live'


Resources:
  miladTestWebhook:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: go1.x
      Handler: main
      AutoPublishAlias: live
      Tracing: Active
      FunctionName: !Join [ "_", [ "milad_test", !Ref PullRequest]]
      DeploymentPreference:
        Type: AllAtOnce
      Environment:
        Variables:
          Suffix: !Ref PullRequest


  DynamoDBTableProducts:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Join [ "_", [ "Products", !Ref PullRequest]]
      AttributeDefinitions:
        - AttributeName: 'productId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'productId'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 20