AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'milad test webhook'

Parameters:
  MyEnvironment:
    Type: String
    Default: testing
    AllowedValues:
      - testing
      - staging
      - prod
    Description: Environemt of this stack


Resources:
  miladTestWebhook:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: go1.x
      Handler: main
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
    Environment:
      Variables:
        DEPLOY_ENVIRONMENT: !Ref: MyEnvironment