AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'milad test webhook'

Resources:
  miladTestWebhook:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: go1.x
      Handler: main
      AutoPublishAlias: live
      Tracing: Active
      DeploymentPreference:
        Type: AllAtOnce
      Environment:
        Variables:
          Env1: '{"REGION": "REGION_VALUE", "ENDPOINT": "http://SOME_ENDPOINT"}'
          Env2: test
          MyEnvironment : stage