AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'The hive of Maya'

Parameters:
  MyEnvironment:
    Type: String
    Default: testing
    AllowedValues:
      - testing
      - staging
      - prod
    Description: Environemt of this stack


Resources:
  miladTestWebhook:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: go1.x
      Handler: main
      AutoPublishAlias: live
      Role:
        Fn::GetAtt: [ MayaLambdaExecutionRole, Arn ]
      DeploymentPreference:
        Type: AllAtOnce
    Environment:
      Variables:
        ENVIRONMENT: !Ref: MyEnvironment


  MayaLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: MiladTestExecutionRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'logs:*'
            - 's3:*'
            - 'dynamodb:*'
            - 'kinesis:*'
            Resource: '*'